// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCifpIHG01f6lBGnHKGnsVKJ42KsmLU0jc',
    appId: '1:934218907924:web:07615d1dd2121a93014201',
    messagingSenderId: '934218907924',
    projectId: 'field-service-management-deac0',
    authDomain: 'field-service-management-deac0.firebaseapp.com',
    storageBucket: 'field-service-management-deac0.firebasestorage.app',
    measurementId: 'G-17E4HBLM59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPvKb5-3HqP8-qMwUAfHjzU66Va019ik',
    appId: '1:934218907924:android:1523bf7424c1b5c4014201',
    messagingSenderId: '934218907924',
    projectId: 'field-service-management-deac0',
    storageBucket: 'field-service-management-deac0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57-kNTihCFMA_4hjeaHjfw1S017xYdCg',
    appId: '1:934218907924:ios:365ef790c79adf9f014201',
    messagingSenderId: '934218907924',
    projectId: 'field-service-management-deac0',
    storageBucket: 'field-service-management-deac0.firebasestorage.app',
    iosBundleId: 'com.example.fieldServiceManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD57-kNTihCFMA_4hjeaHjfw1S017xYdCg',
    appId: '1:934218907924:ios:365ef790c79adf9f014201',
    messagingSenderId: '934218907924',
    projectId: 'field-service-management-deac0',
    storageBucket: 'field-service-management-deac0.firebasestorage.app',
    iosBundleId: 'com.example.fieldServiceManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCifpIHG01f6lBGnHKGnsVKJ42KsmLU0jc',
    appId: '1:934218907924:web:809504765a063942014201',
    messagingSenderId: '934218907924',
    projectId: 'field-service-management-deac0',
    authDomain: 'field-service-management-deac0.firebaseapp.com',
    storageBucket: 'field-service-management-deac0.firebasestorage.app',
    measurementId: 'G-0N2NHXHK7S',
  );
}
